server:
  port: 8070

eureka:
  instance:
    hostname: eurekaserver   # this is fine, or use the container hostname in Docker
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: "http://localhost:8070/eureka/"   # <--- important: override the default "http://localhost:8761/eureka/"