build:
  version: "1.0"

gateway:
  message: "Welcome to CUMS gateway related Test APIs "
  contactDetails:
    name: "LIVTIN"
    email: "livtin@hotmail.com"
  onCallSupport:
    - (855) 92-205520
    - (855) 15-205520