server:
  port: 8074

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka/

eureka:
  instance:
    preferIpAddress: true
