server:
  port: 8074

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eurekaserver:8070/eureka/
  instance:
    prefer-ip-address: true
